@startuml

title __IMPLEMENTATION's Class Diagram__\n

  namespace MTADroneService.DroneService.application {
    namespace services {
      namespace implementation {
        class MTADroneService.DroneService.application.services.implementation.AuthSigningKeyResolverImpl {
            ~ secretKeyString : String
            - secretKey : SecretKey
            + getSecretKey()
            + resolveSigningKey()
            + resolveSigningKey()
        }
      }
    }
  }
  

  namespace MTADroneService.DroneService.application {
    namespace services {
      namespace implementation {
        class MTADroneService.DroneService.application.services.implementation.MissionServiceImpl {
        }
      }
    }
  }
  

  namespace MTADroneService.DroneService.application {
    namespace services {
      namespace implementation {
        class MTADroneService.DroneService.application.services.implementation.RetrieveInfoDroneImpl {
        }
      }
    }
  }
  

  namespace MTADroneService.DroneService.application {
    namespace services {
      namespace implementation {
        class MTADroneService.DroneService.application.services.implementation.ServiceServiceImpl {
            ~ droneDAO : DroneDAO
            ~ missionDAO : MissionDAO
            ~ modelMapper : ModelMapper
            + createMission()
        }
      }
    }
  }
  

  namespace MTADroneService.DroneService.application {
    namespace services {
      namespace implementation {
        class MTADroneService.DroneService.application.services.implementation.TokenServiceImpl {
            ~ authSigningKeyResolver : AuthSigningKeyResolver
            + generateNewToken()
            + validateToken()
        }
      }
    }
  }
  

  namespace MTADroneService.DroneService.application {
    namespace services {
      namespace implementation {
        class MTADroneService.DroneService.application.services.implementation.UserServiceImpl {
            ~ bCryptPasswordEncoder : BCryptPasswordEncoder
            ~ modelMapper : ModelMapper
            ~ tokenService : TokenService
            ~ userDAO : UserDAO
            + createUser()
            + loginUser()
        }
      }
    }
  }
  

  MTADroneService.DroneService.application.services.implementation.AuthSigningKeyResolverImpl .up.|> AuthSigningKeyResolver
  MTADroneService.DroneService.application.services.implementation.MissionServiceImpl .up.|> MissionService
  MTADroneService.DroneService.application.services.implementation.RetrieveInfoDroneImpl .up.|> RetrieveInfoDrone
  MTADroneService.DroneService.application.services.implementation.ServiceServiceImpl .up.|> ServiceService
  MTADroneService.DroneService.application.services.implementation.TokenServiceImpl .up.|> TokenService
  MTADroneService.DroneService.application.services.implementation.UserServiceImpl .up.|> UserService


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
