@startuml

title __IMPLEMENTATION's Class Diagram__\n

  namespace MTADroneService.DroneService.application {
    namespace services {
      namespace implementation {
        class MTADroneService.DroneService.application.services.implementation.AuthSigningKeyResolverImpl {
            ~ secretKeyString : String
            - secretKey : SecretKey
            + getSecretKey()
            + resolveSigningKey()
            + resolveSigningKey()
        }
      }
    }
  }
  

  namespace MTADroneService.DroneService.application {
    namespace services {
      namespace implementation {
        class MTADroneService.DroneService.application.services.implementation.DroneServiceImpl {
            ~ droneDAO : DroneDAO
            ~ logger : Logger
            + getAllDrones()
            + getDroneInfo()
        }
      }
    }
  }
  

  namespace MTADroneService.DroneService.application {
    namespace services {
      namespace implementation {
        class MTADroneService.DroneService.application.services.implementation.MissionServiceImpl {
            ~ logger : Logger
            - missionDAO : MissionDAO
            + getMissionByDroneID()
            + getMissionByID()
            + getMissionDetails()
        }
      }
    }
  }
  

  namespace MTADroneService.DroneService.application {
    namespace services {
      namespace implementation {
        class MTADroneService.DroneService.application.services.implementation.ServiceServiceImpl {
            ~ droneDAO : DroneDAO
            ~ logger : Logger
            ~ missionDAO : MissionDAO
            ~ modelMapper : ModelMapper
            ~ userDAO : UserDAO
            + createMission()
        }
      }
    }
  }
  

  namespace MTADroneService.DroneService.application {
    namespace services {
      namespace implementation {
        class MTADroneService.DroneService.application.services.implementation.TokenServiceImpl {
            ~ authSigningKeyResolver : AuthSigningKeyResolver
            ~ logger : Logger
            + generateNewToken()
            + validateToken()
        }
      }
    }
  }
  

  namespace MTADroneService.DroneService.application {
    namespace services {
      namespace implementation {
        class MTADroneService.DroneService.application.services.implementation.UserServiceImpl {
            ~ bCryptPasswordEncoder : BCryptPasswordEncoder
            ~ logger : Logger
            ~ modelMapper : ModelMapper
            ~ tokenService : TokenService
            ~ userDAO : UserDAO
            + createUser()
            + loginUser()
        }
      }
    }
  }
  

  MTADroneService.DroneService.application.services.implementation.AuthSigningKeyResolverImpl .up.|> AuthSigningKeyResolver
  MTADroneService.DroneService.application.services.implementation.DroneServiceImpl .up.|> DroneService
  MTADroneService.DroneService.application.services.implementation.MissionServiceImpl .up.|> MissionService
  MTADroneService.DroneService.application.services.implementation.ServiceServiceImpl .up.|> ServiceService
  MTADroneService.DroneService.application.services.implementation.TokenServiceImpl .up.|> TokenService
  MTADroneService.DroneService.application.services.implementation.UserServiceImpl .up.|> UserService


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
