apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOnsidXNlcm5hbWUiOiJpYW1nYWJyaWVsYWNocnQiLCJwYXNzd29yZCI6InN0ZWFkZWFyZ2ludDg4QUAiLCJlbWFpbCI6ImdhYnJpZWxhY2hpcml0YWF0bTk3QGdtYWlsLmNvbSIsImF1dGgiOiJhV0Z0WjJGaWNtbGxiR0ZqYUhKME9uTjBaV0ZrWldGeVoybHVkRGc0UVVBPSJ9fX0=
kind: Secret
metadata:
  creationTimestamp: null
  name: regcred
type: kubernetes.io/dockerconfigjson
