@startuml

title __UTILITY's Class Diagram__\n

  namespace MTADroneService.DroneService.application {
    namespace utility {
      class MTADroneService.DroneService.application.utility.DroneCoordinates {
          ~ currentLatitude : String
          ~ currentLongitude : String
          ~ images : List<String>
          ~ missionStatus : String
      }
    }
  }
  

  namespace MTADroneService.DroneService.application {
    namespace utility {
      class MTADroneService.DroneService.application.utility.MissionInfoToSend {
          ~ isTaken : Boolean
          ~ missionLatitude : String
          ~ missionLongitude : String
          ~ missionType : String
          ~ videoURL : String
      }
    }
  }
  

  namespace MTADroneService.DroneService.application {
    namespace utility {
      class MTADroneService.DroneService.application.utility.Utils {
          {static} + currentPosition : Map<String, DroneCoordinates>
          {static} + imageNumber : AtomicInteger
          {static} + missionDetails : Map<String, MissionInfoToSend>
          {static} ~ logger : Logger
          {static} + addMissionInfoToSend()
          {static} + addNewImage()
          {static} + deleteAllCurrentPhotos()
          {static} + deletePhoto()
          {static} + getCurrentDate()
          {static} + getDronePosition()
          {static} + getMissionInfoToSend()
          {static} + saveImage()
          {static} + updateDronePosition()
          {static} + updateMissionStatus()
      }
    }
  }
  

  namespace MTADroneService.DroneService.application {
    namespace utility {
      enum DroneStatus {
        AVAILABLE
        BUSY
      }
    }
  }
  

  namespace MTADroneService.DroneService.application {
    namespace utility {
      enum MissionStatus {
        FINISHED
        FLYING_TO_BASE
        FLYING_TO_INTEREST_POINT
        LANDING
        PREPARING
        SEARCHING_PERSON
      }
    }
  }
  

  namespace MTADroneService.DroneService.application {
    namespace utility {
      enum MissionTypes {
        DELIVERY
        SAR
        SURVEILLANCE
      }
    }
  }
  

  MTADroneService.DroneService.application.utility.Utils +-down- MTADroneService.DroneService.application.utility.Utils.DroneStatus
  MTADroneService.DroneService.application.utility.Utils +-down- MTADroneService.DroneService.application.utility.Utils.MissionStatus
  MTADroneService.DroneService.application.utility.Utils +-down- MTADroneService.DroneService.application.utility.Utils.MissionTypes


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
