server:
    port: 8888

spring:
    data:
        mongodb:
            host: mongodb://localhost:27017
            database: MTADroneServiceclientsDB
jwt:
    secret:
        key: Asdasdasdasdasdsdakshvdaihsvdaisygfaisfgaiufgasoufdhyaoisfyhaopsifhy

