apiVersion: apps/v1
kind: Deployment
metadata:
  name: interface-deployment
  labels:
    name: interface-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      name: interface
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: interface
    spec:
      imagePullSecrets:
        - name:  regcred
      containers:
        - image:  iamgabrielachrt/mtadroneservice:interface
          name:  interface
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name:  SPRING_PROFILES_ACTIVE
              value:  prod
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 40
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 40
      restartPolicy: Always
