apiVersion: v1
kind: Service
metadata:
  name: ingress-service
spec:
  type: LoadBalancer
  selector:
    name: nginx-controller-app
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443
