@startuml

title __CONTROLLER's Class Diagram__\n

  namespace MTADroneService.DroneService.application {
    namespace controller {
      class MTADroneService.DroneService.application.controller.CommunicationController {
          ~ droneService : DroneService
          ~ logger : Logger
          ~ missionDAO : MissionDAO
          ~ missionService : MissionService
          + getCoordinatesToGo()
          + getImage()
          + getStatus()
          + getVideoURL()
          + handleFileUpload()
          + setVideoURL()
          + storeCurrentLocation()
          + updateMissionStatus()
      }
    }
  }
  

  namespace MTADroneService.DroneService.application {
    namespace controller {
      class MTADroneService.DroneService.application.controller.DroneController {
          ~ droneDAO : DroneDAO
          ~ droneService : DroneService
          ~ logger : Logger
          ~ modelMapper : ModelMapper
          ~ getCurrentPosition()
      }
    }
  }
  

  namespace MTADroneService.DroneService.application {
    namespace controller {
      class MTADroneService.DroneService.application.controller.MissionController {
          ~ logger : Logger
          - droneService : DroneService
          - missionService : MissionService
          - modelMapper : ModelMapper
          - userDAO : UserDAO
          + getAllMissions()
          + getMissionDetails()
      }
    }
  }
  

  namespace MTADroneService.DroneService.application {
    namespace controller {
      class MTADroneService.DroneService.application.controller.ServiceController {
          ~ logger : Logger
          ~ serviceService : ServiceService
          + createDeliveryMission()
          + createSearchMission()
          + createSurveilMission()
      }
    }
  }
  

  namespace MTADroneService.DroneService.application {
    namespace controller {
      class MTADroneService.DroneService.application.controller.TokenController {
          ~ logger : Logger
          ~ tokenService : TokenService
          + validateToken()
      }
    }
  }
  

  namespace MTADroneService.DroneService.application {
    namespace controller {
      class MTADroneService.DroneService.application.controller.UserController {
          ~ logger : Logger
          ~ userService : UserService
          {static} - UNKNOWN_USERNAME_OR_BAD_PASSWORD : String
          + createUser()
          + loginUser()
      }
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
